Fix sphinx doc
bearingpoint/bbs-hypercube-api pull request #141
Opened 2021-03-10 07:46 UTC by OlivierLoison

- Fix auto-documentation from docstring
- Re-structuration of docstring

2021-03-10 15:14 UTC, JeromeMaslowski approved these changes

2021-03-10 15:25 UTC, RomainPhil requested changes

2021-03-10 15:25 UTC, RomainPhil commented on HyperAPI/hyper_api/index.rst
>  	!pip install --user <packageName>
can you change the ! with % in front of pip ? 
tested by alain it have change with jupyter notebook version

2021-03-10 16:45 UTC, RomainPhil approved these changes

2021-03-11 15:58 UTC, AlainSenotH3 approved these changes

2021-03-12 10:42 UTC, serkansahinBE approved these changes

2021-03-12 10:42 UTC, merged